# Generated by Django 3.1 on 2021-01-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_professional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroductionCv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
                ('pdf', models.FileField(upload_to='media', verbose_name='PDF')),
            ],
        ),
        migrations.AlterModelOptions(
            name='backendskills',
            options={'verbose_name_plural': 'BackEndSkills'},
        ),
        migrations.AlterModelOptions(
            name='counter',
            options={'verbose_name_plural': 'Counter'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='softskills',
            options={'verbose_name_plural': 'SoftSkills'},
        ),
    ]
