# Generated by Django 3.1 on 2021-01-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_professional', '0002_auto_20210107_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='introductioncv',
            options={'verbose_name_plural': 'Introduction Cv'},
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='link',
            new_name='site_link',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='paragraph',
        ),
        migrations.AddField(
            model_name='projects',
            name='github_link',
            field=models.TextField(default=None),
        ),
    ]
