# Generated by Django 3.1 on 2020-12-17 12:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('the_artist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prime',
            name='image',
        ),
        migrations.AlterField(
            model_name='prime',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 12, 33, 43, 640301, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ImagesPrime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_pics/')),
                ('multiImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_images', to='the_artist.prime')),
            ],
        ),
    ]
