# Generated by Django 3.1 on 2020-12-17 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('the_artist', '0002_auto_20201217_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesprime',
            name='title',
            field=models.CharField(default='titlu', max_length=100),
        ),
        migrations.AlterField(
            model_name='prime',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 12, 43, 41, 684982, tzinfo=utc)),
        ),
    ]
