# Generated by Django 3.1 on 2020-12-17 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('the_artist', '0006_auto_20201217_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomixes',
            name='embed',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prime',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 15, 13, 5, 453354, tzinfo=utc)),
        ),
    ]
