# Generated by Django 3.1 on 2020-12-20 14:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('the_artist', '0010_auto_20201217_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prime',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 14, 1, 24, 556104, tzinfo=utc)),
        ),
    ]
