# Generated by Django 3.1 on 2021-01-07 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('the_artist', '0012_auto_20201220_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prime',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 14, 22, 5, 588430, tzinfo=utc)),
        ),
    ]
