# Generated by Django 3.1 on 2021-01-07 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('the_artist', '0013_auto_20210107_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiomixes',
            options={'verbose_name_plural': 'AudioMixes'},
        ),
        migrations.AlterModelOptions(
            name='biography',
            options={'verbose_name_plural': 'Biography'},
        ),
        migrations.AlterModelOptions(
            name='facebooklive',
            options={'verbose_name_plural': 'FacebookLive'},
        ),
        migrations.AlterModelOptions(
            name='imagesprime',
            options={'verbose_name_plural': 'ImagesPrime'},
        ),
        migrations.AlterModelOptions(
            name='prime',
            options={'verbose_name_plural': 'Prime'},
        ),
        migrations.AlterField(
            model_name='prime',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 16, 23, 5, 208628, tzinfo=utc)),
        ),
    ]
