# Generated by Django 3.1 on 2021-01-11 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('the_artist', '0014_auto_20210107_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prime',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 17, 28, 2, 957360, tzinfo=utc)),
        ),
    ]
